name: Llmsr-Qwen-VL-8b
class_name: LLMSRSearcher
api_type: "vllm"
api_model: "/mnt/hdd_raid5/gaoch/Qwen3-VL-8B-Instruct"
api_url: "http://localhost:{}/v1/"
global_max_sample_num: 1000
samples_per_prompt: 4
num_islands: 10